 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: app-dep
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: myproj
   template:
     metadata:
       labels:
         app: myproj
     spec:
       containers:
       - name: myproj
         image: icr.io/glamtique_01/app
         imagePullPolicy: Always
         ports:
         - containerPort: 5000